import os
from functools import wraps
from pathlib import Path
from uuid import uuid4

import psycopg
from dotenv import load_dotenv
from flask import Flask,flash,g,redirect,render_template,request,url_for,session
from psycopg.rows import dict_row
from supabase import create_client
from werkzeug.security import check_password_hash,generate_password_hash

load_dotenv()

app=Flask(__name__)

app.secret_key=os.getenv("SECRET_KEY")
DATABASE_URL=os.getenv("DATABASE_URL")
SUPABASE_URL=os.getenv("SUPABASE_URL")
SUPABASE_SECRET_KEY=os.getenv("SUPABASE_SECRET_KEY")

BUCKET="game-covers"

if not app.secret_key:
    raise RuntimeError("SECRET_KEY не найден в .env")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL не найден в .env")

if not SUPABASE_URL:
    raise RuntimeError("SUPABASE_URL не найден в .env")

if not SUPABASE_SECRET_KEY:
    raise RuntimeError("SUPABASE_SECRET_KEY не найден в .env")

supabase=create_client(
    SUPABASE_URL,
    SUPABASE_SECRET_KEY
)

ALLOWED_EXTENSIONS={
    ".png",
    ".jpg",
    ".jpeg",
    ".webp"
}

app.config["MAX_CONTENT_LENGTH"]=5*1024*1024


def get_db():
    if "db" not in g:
        g.db=psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row,
            connect_timeout=10
        )

    return g.db


@app.teardown_appcontext
def close_db(error=None):
    db=g.pop("db",None)

    if db is not None:
        db.close()


def init_db():
    db=get_db()

    db.execute(
        """
        CREATE TABLE IF NOT EXISTS users(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL
        )
        """
    )

    db.execute(
        """
        CREATE TABLE IF NOT EXISTS games(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            genre TEXT NOT NULL,
            rating INTEGER NOT NULL CHECK(rating BETWEEN 0 AND 10),
            status TEXT NOT NULL,
            description TEXT NOT NULL,
            image TEXT NOT NULL,
            image_path TEXT,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )

    db.execute(
        """
        ALTER TABLE games
        ADD COLUMN IF NOT EXISTS image_path TEXT
        """
    )

    db.commit()


def allowed_file(filename):
    extension=Path(filename).suffix.lower()
    return extension in ALLOWED_EXTENSIONS


def get_public_url(storage_path):
    public_url=supabase.storage.from_(BUCKET).get_public_url(
        storage_path
    )

    if isinstance(public_url,str):
        return public_url

    if isinstance(public_url,dict):
        return (
            public_url.get("publicUrl")
            or public_url.get("public_url")
        )

    return (
        getattr(public_url,"public_url",None)
        or getattr(public_url,"publicUrl",None)
        or str(public_url)
    )


def upload_cover(image,user_id):
    extension=Path(image.filename).suffix.lower()
    storage_path=f"{user_id}/{uuid4().hex}{extension}"

    content_type=image.mimetype

    if not content_type:
        content_type={
            ".png":"image/png",
            ".jpg":"image/jpeg",
            ".jpeg":"image/jpeg",
            ".webp":"image/webp"
        }.get(extension,"application/octet-stream")

    image.stream.seek(0)

    supabase.storage.from_(BUCKET).upload(
        path=storage_path,
        file=image.stream,
        file_options={
            "content-type":content_type,
            "upsert":"false"
        }
    )

    image_url=get_public_url(storage_path)

    return image_url,storage_path


def delete_cover(storage_path):
    if not storage_path:
        return

    supabase.storage.from_(BUCKET).remove(
        [storage_path]
    )


def login_required(view):
    @wraps(view)
    def wrapped_view(**kwargs):
        if "user_id" not in session:
            return redirect(url_for("login"))

        return view(**kwargs)

    return wrapped_view


@app.route("/register",methods=["GET","POST"])
def register():
    error=None

    if request.method=="POST":
        username=request.form["username"].strip()
        password=request.form["password"]

        if not username:
            error="Введите имя пользователя"

        elif len(password)<6:
            error="Пароль должен содержать минимум 6 символов"

        if error is None:
            db=get_db()

            user=db.execute(
                "SELECT id FROM users WHERE username=%s",
                (username,)
            ).fetchone()

            if user:
                error="Такой пользователь уже существует"

            else:
                password_hash=generate_password_hash(password)

                db.execute(
                    """
                    INSERT INTO users(username,password_hash)
                    VALUES(%s,%s)
                    """,
                    (username,password_hash)
                )

                db.commit()

                flash("Аккаунт создан ✅")

                return redirect(url_for("login"))

    return render_template(
        "register.html",
        error=error
    )


@app.route("/login",methods=["GET","POST"])
def login():
    error=None

    if request.method=="POST":
        username=request.form["username"].strip()
        password=request.form["password"]

        db=get_db()

        user=db.execute(
            "SELECT * FROM users WHERE username=%s",
            (username,)
        ).fetchone()

        if user is None:
            error="Неверное имя пользователя или пароль"

        elif not check_password_hash(user["password_hash"],password):
            error="Неверное имя пользователя или пароль"

        else:
            session.clear()
            session["user_id"]=user["id"]
            session["username"]=user["username"]

            flash("Вы вошли в аккаунт 🎮")

            return redirect(url_for("index"))

    return render_template(
        "login.html",
        error=error
    )


@app.route("/logout")
def logout():
    session.clear()

    flash("Вы вышли из аккаунта")

    return redirect(url_for("login"))


@app.route("/")
@login_required
def index():
    search=request.args.get("q","").strip()
    status_filter=request.args.get("status","").strip()
    sort=request.args.get("sort","newest").strip()

    db=get_db()

    stats=db.execute(
        """
        SELECT
            COUNT(*) AS total,
            SUM(CASE WHEN status='Играю' THEN 1 ELSE 0 END) AS playing,
            SUM(CASE WHEN status='Пройдена' THEN 1 ELSE 0 END) AS completed,
            SUM(CASE WHEN status='Хочу пройти' THEN 1 ELSE 0 END) AS want,
            SUM(CASE WHEN status='Заброшена' THEN 1 ELSE 0 END) AS abandoned
        FROM games
        WHERE user_id=%s
        """,
        (session["user_id"],)
    ).fetchone()

    sql="""
        SELECT *
        FROM games
        WHERE user_id=%s
    """

    params=[session["user_id"]]

    if search:
        sql+=" AND name ILIKE %s"
        params.append(f"%{search}%")

    if status_filter:
        sql+=" AND status=%s"
        params.append(status_filter)

    sort_options={
        "newest":"id DESC",
        "oldest":"id ASC",
        "rating_high":"rating DESC",
        "rating_low":"rating ASC",
        "name_asc":"LOWER(name) ASC",
        "name_desc":"LOWER(name) DESC"
    }

    order_by=sort_options.get(
        sort,
        "id DESC"
    )

    sql+=f" ORDER BY {order_by}"

    rows=db.execute(
        sql,
        params
    ).fetchall()

    games=[
        (game["id"],game)
        for game in rows
    ]

    return render_template(
        "index.html",
        games=games,
        search=search,
        status_filter=status_filter,
        sort=sort,
        stats=stats
    )


@app.route("/add",methods=["GET","POST"])
@login_required
def add_game():
    if request.method=="POST":
        name=request.form.get("name","").strip()
        genre=request.form.get("genre","").strip()
        rating_text=request.form.get("rating","").strip()
        status=request.form.get("status","").strip()
        description=request.form.get("description","").strip()
        image=request.files.get("image")

        if (
            not name
            or not genre
            or not rating_text
            or not status
            or not description
        ):
            return render_template(
                "add_game.html",
                error="Заполни все поля"
            )

        try:
            rating=int(rating_text)

        except ValueError:
            return render_template(
                "add_game.html",
                error="Рейтинг должен быть числом"
            )

        if rating<0 or rating>10:
            return render_template(
                "add_game.html",
                error="Рейтинг должен быть от 0 до 10"
            )

        if image is None or image.filename=="":
            return render_template(
                "add_game.html",
                error="Выбери картинку"
            )

        if not allowed_file(image.filename):
            return render_template(
                "add_game.html",
                error="Разрешены PNG, JPG, JPEG и WEBP"
            )

        try:
            image_url,image_path=upload_cover(
                image,
                session["user_id"]
            )

        except Exception:
            return render_template(
                "add_game.html",
                error="Не удалось загрузить картинку"
            )

        db=get_db()

        try:
            db.execute(
                """
                INSERT INTO games(
                    name,
                    genre,
                    rating,
                    status,
                    description,
                    image,
                    image_path,
                    user_id
                )
                VALUES(%s,%s,%s,%s,%s,%s,%s,%s)
                """,
                (
                    name,
                    genre,
                    rating,
                    status,
                    description,
                    image_url,
                    image_path,
                    session["user_id"]
                )
            )

            db.commit()

        except Exception:
            db.rollback()

            try:
                delete_cover(image_path)
            except Exception:
                pass

            raise

        flash("Игра успешно добавлена 🎮")

        return redirect(
            url_for("index")
        )

    return render_template(
        "add_game.html"
    )


@app.route(
    "/delete/<int:game_id>",
    methods=["POST"]
)
@login_required
def delete_game(game_id):
    db=get_db()

    game=db.execute(
        """
        SELECT *
        FROM games
        WHERE id=%s AND user_id=%s
        """,
        (
            game_id,
            session["user_id"]
        )
    ).fetchone()

    if game is None:
        return redirect(
            url_for("index")
        )

    image_path=game["image_path"]

    db.execute(
        """
        DELETE FROM games
        WHERE id=%s AND user_id=%s
        """,
        (
            game_id,
            session["user_id"]
        )
    )

    db.commit()

    try:
        delete_cover(image_path)
    except Exception:
        pass

    flash("Игра удалена 🗑️")

    return redirect(
        url_for("index")
    )


@app.route("/game/<int:game_id>")
@login_required
def game_details(game_id):
    db=get_db()

    game=db.execute(
        """
        SELECT *
        FROM games
        WHERE id=%s AND user_id=%s
        """,
        (
            game_id,
            session["user_id"]
        )
    ).fetchone()

    if game is None:
        return redirect(
            url_for("index")
        )

    return render_template(
        "game.html",
        game=game,
        game_id=game_id
    )


@app.route(
    "/edit/<int:game_id>",
    methods=["GET","POST"]
)
@login_required
def edit_game(game_id):
    db=get_db()

    game=db.execute(
        """
        SELECT *
        FROM games
        WHERE id=%s AND user_id=%s
        """,
        (
            game_id,
            session["user_id"]
        )
    ).fetchone()

    if game is None:
        return redirect(
            url_for("index")
        )

    if request.method=="POST":
        name=request.form.get("name","").strip()
        genre=request.form.get("genre","").strip()
        rating_text=request.form.get("rating","").strip()
        status=request.form.get("status","").strip()
        description=request.form.get("description","").strip()
        image=request.files.get("image")

        if (
            not name
            or not genre
            or not rating_text
            or not status
            or not description
        ):
            return render_template(
                "edit_game.html",
                game=game,
                game_id=game_id,
                error="Заполни все поля"
            )

        try:
            rating=int(rating_text)

        except ValueError:
            return render_template(
                "edit_game.html",
                game=game,
                game_id=game_id,
                error="Рейтинг должен быть числом"
            )

        if rating<0 or rating>10:
            return render_template(
                "edit_game.html",
                game=game,
                game_id=game_id,
                error="Рейтинг должен быть от 0 до 10"
            )

        image_url=game["image"]
        image_path=game["image_path"]

        new_image_path=None
        old_image_path=image_path

        if image is not None and image.filename!="":
            if not allowed_file(image.filename):
                return render_template(
                    "edit_game.html",
                    game=game,
                    game_id=game_id,
                    error="Разрешены PNG, JPG, JPEG и WEBP"
                )

            try:
                image_url,new_image_path=upload_cover(
                    image,
                    session["user_id"]
                )

                image_path=new_image_path

            except Exception:
                return render_template(
                    "edit_game.html",
                    game=game,
                    game_id=game_id,
                    error="Не удалось загрузить картинку"
                )

        try:
            db.execute(
                """
                UPDATE games
                SET
                    name=%s,
                    genre=%s,
                    rating=%s,
                    status=%s,
                    description=%s,
                    image=%s,
                    image_path=%s
                WHERE id=%s AND user_id=%s
                """,
                (
                    name,
                    genre,
                    rating,
                    status,
                    description,
                    image_url,
                    image_path,
                    game_id,
                    session["user_id"]
                )
            )

            db.commit()

        except Exception:
            db.rollback()

            if new_image_path:
                try:
                    delete_cover(new_image_path)
                except Exception:
                    pass

            raise

        if new_image_path and old_image_path:
            try:
                delete_cover(old_image_path)
            except Exception:
                pass

        flash("Изменения сохранены ✅")

        return redirect(
            url_for(
                "game_details",
                game_id=game_id
            )
        )

    return render_template(
        "edit_game.html",
        game=game,
        game_id=game_id
    )


with app.app_context():
    init_db()


@app.route("/robots.txt")
def robots_txt():
    return """User-agent: *
Allow: /
Sitemap: https://gamevault-1-dt2g.onrender.com/sitemap.xml
""", 200, {"Content-Type": "text/plain; charset=utf-8"}

@app.route("/sitemap.xml")
def sitemap():
    return """<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://gamevault-1-dt2g.onrender.com/</loc>
    </url>
</urlset>
""", 200, {"Content-Type": "application/xml; charset=utf-8"}

if __name__=="__main__":
    app.run(
        host="0.0.0.0",
        port=5001,
        debug=False
    )
