import os
import sqlite3
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from psycopg.rows import dict_row

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent
SQLITE_FILE = BASE_DIR / "games.db"
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL не найден в .env")

sqlite_db = sqlite3.connect(SQLITE_FILE)
sqlite_db.row_factory = sqlite3.Row

postgres_db = psycopg.connect(
    DATABASE_URL,
    row_factory=dict_row
)

postgres_db.execute(
    '''
    CREATE TABLE IF NOT EXISTS users(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL
    )
    '''
)

postgres_db.execute(
    '''
    CREATE TABLE IF NOT EXISTS games(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        genre TEXT NOT NULL,
        rating INTEGER NOT NULL CHECK(rating BETWEEN 0 AND 10),
        status TEXT NOT NULL,
        description TEXT NOT NULL,
        image TEXT NOT NULL,
        user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
    )
    '''
)

postgres_db.commit()

cloud_users = postgres_db.execute(
    "SELECT COUNT(*) AS count FROM users"
).fetchone()["count"]

cloud_games = postgres_db.execute(
    "SELECT COUNT(*) AS count FROM games"
).fetchone()["count"]

if cloud_users > 0 or cloud_games > 0:
    postgres_db.close()
    sqlite_db.close()
    raise RuntimeError(
        "В PostgreSQL уже есть данные. Миграция остановлена, чтобы не создать дубликаты."
    )

sqlite_users = sqlite_db.execute(
    "SELECT * FROM users ORDER BY id"
).fetchall()

user_id_map = {}

for user in sqlite_users:
    new_user = postgres_db.execute(
        '''
        INSERT INTO users(username,password_hash)
        VALUES(%s,%s)
        RETURNING id
        ''',
        (
            user["username"],
            user["password_hash"]
        )
    ).fetchone()

    user_id_map[user["id"]] = new_user["id"]

sqlite_games = sqlite_db.execute(
    "SELECT * FROM games ORDER BY id"
).fetchall()

migrated_games = 0
skipped_games = 0

for game in sqlite_games:
    old_user_id = game["user_id"]

    if old_user_id is None or old_user_id not in user_id_map:
        skipped_games += 1
        continue

    postgres_db.execute(
        '''
        INSERT INTO games(
            name,
            genre,
            rating,
            status,
            description,
            image,
            user_id
        )
        VALUES(%s,%s,%s,%s,%s,%s,%s)
        ''',
        (
            game["name"],
            game["genre"],
            game["rating"],
            game["status"],
            game["description"],
            game["image"],
            user_id_map[old_user_id]
        )
    )

    migrated_games += 1

postgres_db.commit()

print(f"Пользователей перенесено: {len(sqlite_users)}")
print(f"Игр перенесено: {migrated_games}")
print(f"Игр без пользователя пропущено: {skipped_games}")
print("Миграция завершена")

postgres_db.close()
sqlite_db.close()
